### ISSUE TITLE
orgalorg asks for key passphrase

### ISSUE THREAD

**Issue by mkevac** [reconquest/orgalorg#10]
Hi.

Orgalorg asks for key passphrase, even though I have already entered it and it's not needed via simple ssh.

Can orgalorg use same saved passphrase?

This works without passphrase:

```
$ ssh foobar1.mlan
```

This does not:

```
$ orgalorg -o foobar1.mlan -o foobar2.mlan -C "uname -a"
Key passphrase: 
```

**Comment by kovetskiy** [comment]
@mkevac orgalorg doesn't use libssh.

**Comment by seletskiy** [comment]
@mkevac: Reason for that is that `ssh-agent` support is not embedded into `orgalorg`. `ssh-agent` is the reason why you enter password only once, and all encryption which uses the key is actually goes through `ssh-agent` instead of `ssh`.

However, `ssh-agent` implementation is available in the Go-lang (https://godoc.org/golang.org/x/crypto/ssh/agent), so it should be quite trivially to embed it. I'm glad to merge PR providing that.

**Comment by kovetskiy** [comment]
closed by https://github.com/reconquest/orgalorg/commit/ed1e994d72bbd39ea729c21bbd6cbb7294ab6c36
