### ISSUE TITLE
The name of this tool is too hard to pronounce

### ISSUE THREAD

**Issue by iofxl** [reconquest/orgalorg#21]
Should change to <og> or <ogssh> or <orgssh > or <oh my god ssh> such easy name  else just for simple?

**Comment by jinlongplus** [comment]
og or ogssh or orgssh or oh-my-god-ssh

**Comment by kovetskiy** [comment]
@jinlongplus probably, it depends on your native language because for me it's easy to pronounce - vowel before/after every consonant letter. 

There is a history behind of this name, Orgalorg was implemented when we started using Gunter for configuring our cluster: https://github.com/reconquest/gunter

The metaphoric history of Gunter and Orgalorg is described here: http://adventuretime.wikia.com/wiki/Orgalorg

If you just need a short name, you can use any. I use `o` as zsh alias.

**Comment by jinlongplus** [comment]
OK ,  Thank you let me know. 
I'll alias as o.
